previewsEnabled: true
services:
  - type: web
    name: handlefinder-backend
    repo: https://github.com/AYOMITIDE-OAJ/socialsFinder
    region: ohio
    env: python
    plan: starter
    numInstances: 1
    buildCommand: pip install -r requirements.txt
    startCommand: sh scripts/start.sh
    healthCheckPath: /api/v1/test
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
